# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef5b3701d1aa78fed4cdc2894cb507060e8b49c0a4de775249ce5fca9bd4d66aa5cf0da0588408cf90e7f06c232be1150a955d92bb10d9f488f3d1988bd31329

test:
  secret_key_base: df67882c3de9c18892cf910e2361240c4e339b9586190ce233510f7c960b1bc88b77a230c66fd23b61fb9f402a388f4412e701f4ed8485ceec672c4d17a9da9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
